### ISSUE TITLE
CI on pr only is not working on Azure DevOps Repo and Azure DevOps Pipeline

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [Azure/arc-cicd-demo-src#26]
This code snippet is not working on Azure Repoes.

https://github.com/Azure/arc-cicd-demo-src/blob/master/.pipelines/az-vote-pr-pipeline.yaml#L3-L7

```
trigger: none
pr:
  branches:
    include:
        - master
```

```
Git Source: Azure DevOps Repo
CI/CD: Azure DevOps Pipeline
```
